name: Run Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  check_test_all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup uv
        uses: astral-sh/setup-uv@v10

      - name: Run tests
        run: uv run python -m unittest discover --start-directory tests
